manifest:
  version: 1.0
  self:
    path: app

  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: v4.4.0
      import:
        name-allowlist:
          - cmsis_6
          - hal_stm32
          - hal_espressif
          - segger
